Make the endpoint id configurable
carlrygart/portainer-stack-deploy pull request #14
Opened 2021-11-24 20:49 UTC by DaniFoldi

Hi,

I'm glad this project exists, it simplified my deployment action a lot. I have a Portainer setup with multiple environments, and I had to deploy a stack to one that has an id > 1 (so not the default). I'm not that familiar with TS, so I'm pretty sure there are better ways to write this (hence the draft), however here is the code that I have now tested to be working.

2021-11-25 06:54 UTC, carlrygart commented
Looks good! I actually considered adding this option when I created the project, but scoped it out since I didn't need it at the time. This is a great contribution! I will take a look later today so it works properly with my other setups (shouldn't be a problem) and then update all dependencies and bump the released version. Is that okay, or are you in a hurry? :)

2021-11-25 07:59 UTC, DaniFoldi commented
Thanks! Please take your time testing it, I just thought that maybe the value should be optional, and default to 1 to maintain compatibility with existing workflows?

2021-12-04 21:48 UTC, carlrygart requested changes
Really well done! Sorry I didn't have time to look at this earlier. I tried it out with my pipelines and it is not backwards compatible right now because of the required endpoint-id input. I suggest that we make this input optional and that we default to 1. I added some other comments as well. Do you want to fix them yourself or should I?

2021-12-04 21:48 UTC, carlrygart commented on __tests__/deployStack.test.ts
> +        endpointId: '1',
Let's create a proper test for this case.

2021-12-04 21:48 UTC, carlrygart commented on action.yml
> +    required: true
Can we make this optional instead and then default to 1 to ensure backward compatible?

2021-12-04 21:48 UTC, carlrygart commented on action.yml
> +  variables:
Can we call this one `template-variables` instead?

2021-12-04 21:48 UTC, carlrygart commented on src/deployStack.ts
> +  endpointId: string
Let's make this one a number instead and then do the `parseInt` and set default to 1 inside `main.ts`.

2021-12-04 21:48 UTC, carlrygart commented on src/deployStack.ts
> +  variables?: string
Can we parse this one in `main.ts` instead?

2021-12-04 21:48 UTC, carlrygart commented on src/deployStack.ts
> +    const template = Handlebars.compile(stackDefinition)
Very nice! :)

2021-12-04 21:48 UTC, carlrygart commented on src/deployStack.ts
>      core.info(`No new image provided, using existing stack definition`)
Change this to `No new image provided. Will use image in stack definition.`

2021-12-28 19:25 UTC, carlrygart commented
@DaniFoldi Do you want to fix these changes or do you want me to fix them for you? In that case, let me know if you think it's okay for me to push to your branch (which is your master branch) branch or if I should create a separate branch.

2021-12-28 21:29 UTC, DaniFoldi commented
Hi, it's been a busy period for me, so if you have some free time, feel free to push any changes, if you get around to it

2022-01-23 14:38 UTC, DaniFoldi commented
@carlrygart all the comments should have been implemented now, including a test case for endpoint ids

2022-02-04 14:24 UTC, Tim-Ganther commented
Hi there, any updates regarding the merge? I am looking forward to the feature

2022-02-04 21:30 UTC, carlrygart approved these changes

2022-02-04 21:31 UTC, merged

2022-02-04 21:32 UTC, carlrygart commented
@DaniFoldi Merged now :) Again, thanks a lot for the help! 👏 Will do some minor changes now a release a new version soon.